### PR TITLE
Give installed libraries execute permissions

### PR DESCRIPTION
**Pull request by cottsay**
All shared object libraries should have execute permissions. Using install will default the permissions to be like a normal file, which typically doesn't have execute permissions.

There is no cmake directive for installing libraries in this way, but the PROGRAMS directive is the same as FILES except that it gives execute permissions to installed files.

This was caught as a packaging error on Fedora.

Thanks!

### CODE REVIEW

**Comment by k-okada** [comment]
@130s do you have time to merge this and release new deb? if not I'll take care of this ( but I thinks you will check if this wont brake nextage/hiro more carefully than I do)

**Comment by 130s** [comment]
I'm still trying to build locally. I think we need to check testcases in
downstream packages with AT LEAST simulation before making a release (we
need a rule here).

**Comment by k-okada** [comment]
can we use ros devel test for downstream packages?

**Comment by 130s** [comment]
Sorry I didn't know this thread was a PReq. I'm now building this locally, as well as [pre-release on the farm](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/1/).

**Comment by 130s** [comment]
Local build passes and [test_openrtm_aist.test](https://github.com/start-jsk/openrtm_aist_core/blob/master/openrtm_aist/test/test_openrtm_aist.test) succeeds. @k-okada is this good enough?

```
[openrtm_aist.rosunit-openrtm_compile_test/test_compile_pkg_config][passed]
[openrtm_aist.rosunit-openrtm_compile_test/test_compile_rtm_config][passed]
[openrtm_aist.rosunit-openrtm_compile_test/test_example][passed]
[openrtm_aist.rosunit-openrtm_compile_test/test_share][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 4
 * ERRORS: 0
 * FAILURES: 0
```

**Comment by k-okada** [comment]
it's ok for me.

**Pull request merged**
